import React,{useEffect,useMemo,useState}from"react";
import{API_BASE}from"../apiClient";
import"./BookingPage.css";

type Location={id:string;name:string};
type Service={id:string;name:string;duration_minutes:number;price:number|string;category_name?:string};
type Employee={id:string;full_name:string;photo_url?:string|null};
type Slot={employee_id:string;employee_name:string;start:string;end:string};
const api=(path:string,init?:RequestInit)=>fetch(`${API_BASE}${path}`,{headers:{"Content-Type":"application/json",...(init?.headers||{})},...init}).then(async r=>{const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`API hiba: ${r.status}`);return data});
const ymd=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;

export function BookingPage(){
 const[locations,setLocations]=useState<Location[]>([]),[locationId,setLocationId]=useState("");
 const[services,setServices]=useState<Service[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[serviceIds,setServiceIds]=useState<string[]>([]),[employeeId,setEmployeeId]=useState("");
 const[date,setDate]=useState(ymd(new Date())),[slots,setSlots]=useState<Slot[]>([]),[slot,setSlot]=useState<Slot|null>(null);
 const[name,setName]=useState(""),[phone,setPhone]=useState(""),[email,setEmail]=useState(""),[note,setNote]=useState(""),[marketing,setMarketing]=useState(false);
 const[loading,setLoading]=useState(false),[error,setError]=useState(""),[done,setDone]=useState<any>(null),[waitDone,setWaitDone]=useState(false);
 useEffect(()=>{api("/api/public/booking/catalog").then(d=>setLocations(d.locations||[])).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!locationId){setServices([]);setEmployees([]);return}setLoading(true);api(`/api/public/booking/catalog?location_id=${encodeURIComponent(locationId)}`).then(d=>{setServices(d.services||[]);setEmployees(d.employees||[]);setServiceIds([]);setEmployeeId("");setSlots([]);setSlot(null)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[locationId]);
 const selected=useMemo(()=>services.filter(s=>serviceIds.includes(s.id)),[services,serviceIds]);
 const total=useMemo(()=>selected.reduce((a,s)=>a+Number(s.price||0),0),[selected]);
 const duration=useMemo(()=>selected.reduce((a,s)=>a+Number(s.duration_minutes||30),0),[selected]);
 const categories=useMemo(()=>Array.from(new Set(services.map(s=>s.category_name||"Egyéb"))),[services]);
 const search=async()=>{if(!locationId||!serviceIds.length)return;setLoading(true);setError("");setSlot(null);try{const q=new URLSearchParams({location_id:locationId,date,service_ids:serviceIds.join(",")});if(employeeId)q.set("employee_id",employeeId);const d=await api(`/api/public/booking/availability?${q}`);setSlots(d.slots||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const submit=async()=>{if(!slot||!name||(!phone&&!email))return setError("Név és telefonszám vagy e-mail szükséges.");setLoading(true);setError("");try{const d=await api("/api/public/booking/book",{method:"POST",body:JSON.stringify({location_id:locationId,employee_id:slot.employee_id,service_ids:serviceIds,client_name:name,phone,email,start_time:slot.start,note,marketing_consent:marketing})});setDone(d)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const waitlist=async()=>{if(!name||(!phone&&!email))return setError("A várólistához is szükséges elérhetőség.");setLoading(true);setError("");try{await api("/api/public/booking/waitlist",{method:"POST",body:JSON.stringify({location_id:locationId,employee_id:employeeId||null,service_ids:serviceIds,client_name:name,phone,email,preferred_from:`${date}T00:00:00`,preferred_to:`${date}T23:59:59`,note})});setWaitDone(true)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 if(done)return <main className="online-booking-page"><section className="booking-success"><span>✓</span><h1>Foglalási igény rögzítve</h1><p>{done.confirmation_required?"A szalon munkatársa ellenőrzi az időpontot, majd visszaigazolást küld.":"Az időpont visszaigazolva."}</p><b>Foglalási azonosító: {done.id}</b><small>Online kedvezmény: {done.online_discount_percent||0}%</small></section></main>;
 return <main className="online-booking-page"><header className="booking-hero"><span>ONLINE IDŐPONTFOGLALÁS</span><h1>Foglaljon időpontot néhány lépésben</h1><p>Válasszon szalont, szolgáltatásokat, szakembert és valós időben elérhető időpontot.</p></header>
 {error&&<div className="booking-public-error">{error}</div>}
 <div className="booking-public-grid"><section className="booking-public-card"><h2>1. Szalon és szolgáltatás</h2><label>Szalon<select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Válasszon szalont</option>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 {categories.map(cat=><div className="booking-service-group" key={cat}><h3>{cat}</h3>{services.filter(s=>(s.category_name||"Egyéb")===cat).map(s=><label className={serviceIds.includes(s.id)?"selected":""} key={s.id}><input type="checkbox" checked={serviceIds.includes(s.id)} onChange={()=>setServiceIds(v=>v.includes(s.id)?v.filter(id=>id!==s.id):[...v,s.id])}/><span><b>{s.name}</b><small>{s.duration_minutes||30} perc · {Number(s.price||0).toLocaleString("hu-HU")} Ft</small></span></label>)}</div>)}
 {selected.length>0&&<div className="booking-summary"><b>{selected.length} szolgáltatás · {duration} perc</b><strong>{total.toLocaleString("hu-HU")} Ft</strong></div>}</section>
 <section className="booking-public-card"><h2>2. Szakember és időpont</h2><label>Szakember<select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">Bármelyik elérhető szakember</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label>Dátum<input type="date" min={ymd(new Date())} value={date} onChange={e=>setDate(e.target.value)}/></label><button className="booking-search-button" disabled={!serviceIds.length||loading} onClick={search}>{loading?"Keresés…":"Szabad időpontok keresése"}</button>
 <div className="booking-slots">{slots.map(s=><button className={slot?.start===s.start&&slot.employee_id===s.employee_id?"selected":""} key={`${s.employee_id}-${s.start}`} onClick={()=>setSlot(s)}><b>{new Date(s.start).toLocaleTimeString("hu-HU",{hour:"2-digit",minute:"2-digit"})}</b><small>{s.employee_name}</small></button>)}</div>{!loading&&serviceIds.length>0&&slots.length===0&&<div className="booking-no-slots"><p>Nincs szabad időpont ezen a napon.</p><button onClick={waitlist} disabled={!name||(!phone&&!email)}>Kérek várólistát</button>{waitDone&&<small>Várólista-igény rögzítve.</small>}</div>}</section>
 <section className="booking-public-card"><h2>3. Vendégadatok</h2><label>Név<input value={name} onChange={e=>setName(e.target.value)} placeholder="Teljes név"/></label><label>Telefonszám<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+36..."/></label><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@pelda.hu"/></label><label>Megjegyzés<textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Opcionális megjegyzés"/></label><label className="booking-consent"><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)}/><span>Hozzájárulok marketing célú kapcsolattartáshoz.</span></label>{slot&&<div className="booking-final"><p><b>{new Date(slot.start).toLocaleDateString("hu-HU")}</b> · {new Date(slot.start).toLocaleTimeString("hu-HU",{hour:"2-digit",minute:"2-digit"})}</p><small>{slot.employee_name}</small></div>}<button className="booking-submit" disabled={!slot||loading} onClick={submit}>{loading?"Mentés…":"Foglalás véglegesítése"}</button></section></div>
 </main>;
}
