import React,{useEffect,useMemo,useState}from"react";
import{Link,useParams}from"react-router-dom";
import PublicPageHero from"../components/PublicPageHero";
import{API_BASE}from"../apiClient";
import{SERVICE_PAGE_BY_SLUG,SERVICE_PAGES}from"../data/servicePages";
import{EXTRA_SERVICE_PAGE_BY_SLUG,EXTRA_SERVICE_PAGES}from"../data/serviceSeoExtras";

const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
type DynamicService={id:string;name:string;duration_minutes:number;category_name:string;department_name:string;base_price:number|string;level_prices?:{normal?:number|null;top?:number|null;master?:number|null}};
const ALL_SERVICE_PAGES=[...SERVICE_PAGES,...EXTRA_SERVICE_PAGES];
const ALL_SERVICE_PAGE_BY_SLUG=new Map(ALL_SERVICE_PAGES.map(item=>[item.slug,item]));
const money=(value:number|null|undefined)=>value==null?"—":`${Math.round(Number(value)).toLocaleString("hu-HU")} Ft`;
const bookingHref=(service:DynamicService|null|undefined,name:string)=>service?.id?`/booking?service_id=${encodeURIComponent(service.id)}&service_name=${encodeURIComponent(name)}&source=service-page`:`/booking?service_name=${encodeURIComponent(name)}&source=service-page`;
const CSS=`
.service-detail-facts{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin-top:26px}.service-detail-fact{padding:20px;border:1px solid #eadfd5;border-radius:16px;background:#fff}.service-detail-fact small{display:block;color:#b69861;font-size:10px;font-weight:850;letter-spacing:.08em;text-transform:uppercase}.service-detail-fact h3{margin:8px 0 9px;font-size:18px}.service-detail-fact p{margin:0;color:#716960;font-size:13px;line-height:1.6}.service-price-box{margin-top:28px;overflow:hidden;border:1px solid #e8ded5;border-radius:18px;background:#fff}.service-price-head,.service-price-row{display:grid;grid-template-columns:minmax(180px,1.4fr) repeat(3,minmax(110px,1fr));align-items:center}.service-price-head{background:#f8f3ee;color:#6f655e;font-size:10px;font-weight:850;text-transform:uppercase;letter-spacing:.06em}.service-price-head>div,.service-price-row>div{padding:13px 15px;border-right:1px solid #eee5dd}.service-price-head>div:last-child,.service-price-row>div:last-child{border-right:0}.service-price-row{border-top:1px solid #eee5dd;font-size:13px}.service-price-row strong{font-size:14px}.service-important-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin-top:24px}.service-important-card{padding:20px;border:1px solid #eadfd5;border-radius:16px;background:#fff}.service-important-card h3{margin:0 0 8px;font-size:17px}.service-important-card p{margin:0;color:#716960;font-size:13px;line-height:1.6}.service-booking-path{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:20px 0 0}.service-booking-path div{padding:14px;border:1px solid #eadfd5;border-radius:14px;background:#fff}.service-booking-path small,.service-booking-path b{display:block}.service-booking-path small{color:#ec008c;font-size:9px;font-weight:850;letter-spacing:.08em}.service-booking-path b{margin-top:4px;font-size:12px}@media(max-width:900px){.service-detail-facts,.service-booking-path{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:620px){.service-detail-facts,.service-important-grid,.service-booking-path{grid-template-columns:1fr}.service-price-box{overflow-x:auto}.service-price-head,.service-price-row{min-width:650px}}
`;
function matchesStaticService(slug:string,title:string,service:DynamicService){const n=normalize(service.name),t=normalize(title);if(slug==="gellakk")return n.includes("gel-lakk")||n.includes("gellakk");if(slug==="japan-manikur")return n.includes("japan")&&n.includes("manikur");return n===normalize(slug)||n===t||n.includes(t)||t.includes(n)}

export function ServiceDetailPage(){
  const{slug=""}=useParams();const normalizedSlug=slug.toLowerCase();const staticService=SERVICE_PAGE_BY_SLUG.get(normalizedSlug)||EXTRA_SERVICE_PAGE_BY_SLUG.get(normalizedSlug);
  const[dynamicService,setDynamicService]=useState<DynamicService|null>(null),[matchedPrice,setMatchedPrice]=useState<DynamicService|null>(null),[loading,setLoading]=useState(!staticService);
  useEffect(()=>{let active=true;if(!staticService)setLoading(true);fetch(`${API_BASE}/api/public/booking/v4/pricelist`,{credentials:"include"}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.error||"A szolgáltatás adatai nem tölthetők be.");return d}).then(data=>{if(!active)return;const services=(data.services||[])as DynamicService[];if(staticService){setMatchedPrice(services.find(s=>matchesStaticService(staticService.slug,staticService.title,s))||null)}else{const found=services.find(s=>normalize(s.name)===normalize(slug))||null;setDynamicService(found);setMatchedPrice(found)}}).catch(()=>{if(active){setDynamicService(null);setMatchedPrice(null)}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[slug,staticService]);
  const seo=useMemo(()=>staticService?{title:staticService.title,description:staticService.lead,canonicalSlug:staticService.slug,category:staticService.category}:dynamicService?{title:dynamicService.name,description:`${dynamicService.name} a Kleopátra Szépségszalonokban. Ismerd meg a szolgáltatást, az időtartamot, az árakat és foglalj online időpontot.`,canonicalSlug:normalize(dynamicService.name),category:dynamicService.category_name}:null,[staticService,dynamicService]);
  useEffect(()=>{if(!seo)return;const previousTitle=document.title;const ensureMeta=(selector:string,name:string)=>{const existing=document.head.querySelector(selector)as HTMLMetaElement|null,created=!existing,meta=existing||document.createElement("meta");if(created){if(name.startsWith("og:"))meta.setAttribute("property",name);else meta.name=name;document.head.appendChild(meta)}return{meta,created,previous:meta.content||""}};const description=ensureMeta('meta[name="description"]',"description"),ogTitle=ensureMeta('meta[property="og:title"]',"og:title"),ogDescription=ensureMeta('meta[property="og:description"]',"og:description"),ogType=ensureMeta('meta[property="og:type"]',"og:type");const existingCanonical=document.head.querySelector('link[rel="canonical"]')as HTMLLinkElement|null,canonicalWasCreated=!existingCanonical,canonical=existingCanonical||document.createElement("link"),previousCanonical=existingCanonical?.href||"";if(canonicalWasCreated){canonical.rel="canonical";document.head.appendChild(canonical)}const canonicalUrl=`https://www.kleoszalon.hu/szolgaltatasok/${seo.canonicalSlug}`;document.title=`${seo.title} | Kleopátra Szépségszalonok`;description.meta.content=seo.description;ogTitle.meta.content=document.title;ogDescription.meta.content=seo.description;ogType.meta.content="website";canonical.href=canonicalUrl;const script=document.createElement("script");script.type="application/ld+json";script.setAttribute("data-kleo-service-jsonld","true");script.text=JSON.stringify({"@context":"https://schema.org","@graph":[{"@type":"Service","name":seo.title,"description":seo.description,"serviceType":seo.category,"url":canonicalUrl,"provider":{"@type":"Organization","name":"Kleopátra Szépségszalonok","url":"https://www.kleoszalon.hu/"}},{"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Kezdőoldal","item":"https://www.kleoszalon.hu/"},{"@type":"ListItem","position":2,"name":"Szolgáltatások","item":"https://www.kleoszalon.hu/szolgaltatasok"},{"@type":"ListItem","position":3,"name":seo.title,"item":canonicalUrl}]}]});document.head.appendChild(script);return()=>{document.title=previousTitle;[description,ogTitle,ogDescription,ogType].forEach(({meta,created,previous})=>{if(created)meta.remove();else meta.content=previous});if(canonicalWasCreated)canonical.remove();else canonical.href=previousCanonical;script.remove()}},[seo]);
  if(loading&&!staticService)return<main><section className="public-section"><div className="container"><div className="notice-card">Szolgáltatás betöltése…</div></div></section></main>;
  if(!staticService&&!dynamicService)return<main><section className="public-section"><div className="container public-cta"><div><h2>A szolgáltatás jelenleg nem érhető el</h2><p>Nézd meg a teljes szolgáltatás- és árlistát.</p></div><Link to="/prices" className="btn btn-primary">Áraink és szolgáltatásaink</Link></div></section></main>;
  if(staticService){const related=(staticService.related||[]).map(x=>ALL_SERVICE_PAGE_BY_SLUG.get(x)).filter(Boolean),normal=matchedPrice?Number(matchedPrice.level_prices?.normal??matchedPrice.base_price??0):null,duration=matchedPrice?.duration_minutes||null,book=bookingHref(matchedPrice,staticService.title);return<main><style>{CSS}</style>
    <PublicPageHero eyebrow={staticService.eyebrow} title={staticService.title} lead={<p>{staticService.lead}</p>} actions={<><Link to={book} className="btn btn-primary">Szalon és időpont választása</Link><Link to="/araink" className="btn btn-outline">Árak</Link></>}/>
    <section className="public-section"><div className="container"><div className="public-section__header"><p className="section-eyebrow">{staticService.category}</p><h2>Minden fontos információ egy helyen</h2><p>{staticService.description}</p></div><div className="service-detail-facts"><article className="service-detail-fact"><small>Mi a szolgáltatás?</small><h3>{staticService.title}</h3><p>{staticService.description}</p></article><article className="service-detail-fact"><small>Kinek ajánlott?</small><h3>Személyre szabható</h3><p>Azoknak, akik a {staticService.category.toLowerCase()} területén személyre szabott, szakemberrel egyeztetett megoldást keresnek.</p></article><article className="service-detail-fact"><small>Hogyan történik?</small><h3>Konzultációtól a befejezésig</h3><p>A szolgáltatás rövid egyeztetéssel indul, majd a szakember az adott kezelés szakmai protokollja és az egyéni igények szerint végzi el.</p></article><article className="service-detail-fact"><small>Időtartam és ár</small><h3>{duration?`${duration} perc`:"Szolgáltatás szerint"}</h3><p>{normal!=null&&normal>0?`${money(normal)}-tól. A pontos Normál, TOP és Master ár szalon és szakember szerint változhat.`:"Az aktuális időtartamot és árakat a böngészhető árlistában mutatjuk szalon és szakemberi szint szerint."}</p></article></div>{matchedPrice&&<div className="service-price-box"><div className="service-price-head"><div>Szolgáltatás</div><div>Normál</div><div>TOP</div><div>Master</div></div><div className="service-price-row"><div><strong>{matchedPrice.name}</strong><br/><small>{matchedPrice.duration_minutes?`${matchedPrice.duration_minutes} perc`:"Aktuális időtartam"}</small></div><div>{money(matchedPrice.level_prices?.normal??Number(matchedPrice.base_price||0))}</div><div>{money(matchedPrice.level_prices?.top)}</div><div>{money(matchedPrice.level_prices?.master)}</div></div></div>}<div className="service-booking-path"><div><small>1. KÉSZ</small><b>{staticService.title}</b></div><div><small>2. KÖVETKEZIK</small><b>Szalon választása</b></div><div><small>3. UTÁNA</small><b>Elérhető szakember</b></div><div><small>4. VÉGÜL</small><b>Szabad időpont</b></div></div></div></section>
    <section className="public-section public-section--soft"><div className="container"><header className="public-section__header"><p className="section-eyebrow">Fontos tudnivalók</p><h2>Mire számíthatsz?</h2></header><div className="service-important-grid">{staticService.benefits.map(benefit=><article className="service-important-card" key={benefit}><h3>{benefit}</h3><p>Az aktuális elérhetőség, technika, időtartam és pontos szolgáltatási tartalom a választott szalon és szakember alapján változhat.</p></article>)}</div></div></section>
    {related.length>0&&<section className="public-section"><div className="container"><header className="public-section__header"><p className="section-eyebrow">Kapcsolódó kezelések</p><h2>Fedezd fel a kapcsolódó szolgáltatásokat</h2></header><div className="feature-grid">{related.map(item=>item&&<Link key={item.slug} to={`/szolgaltatasok/${item.slug}`} className="feature-card card--service"><span className="feature-card__kicker">{item.category}</span><h3>{item.title}</h3><p>{item.lead}</p><span className="link-btn">Részletek →</span></Link>)}</div></div></section>}
    <section className="public-section public-section--soft"><div className="container public-cta"><div><h2>Most már csak a hely és az idő kell</h2><p>A szolgáltatást megtartjuk. A következő oldalon válassz szalont, az adott napon ténylegesen elérhető szakembert, majd szabad időpontot.</p></div><div className="public-page-hero__actions"><Link to="/prices" className="btn btn-outline">Árak összehasonlítása</Link><Link to={book} className="btn btn-primary">Tovább a szalonválasztáshoz</Link></div></div></section></main>}
  const s=dynamicService!,normal=Number(s.level_prices?.normal??s.base_price??0),book=bookingHref(s,s.name);return<main><style>{CSS}</style><PublicPageHero eyebrow={`${s.department_name} · ${s.category_name}`} title={s.name} lead={<p>Részletes tájékoztató a szolgáltatásról, az időtartamról, az árkategóriákról és az online foglalás lehetőségéről.</p>} actions={<><Link to={book} className="btn btn-primary">Szalon és időpont választása</Link><Link to="/prices" className="btn btn-outline">Árlista</Link></>}/><section className="public-section"><div className="container"><header className="public-section__header"><p className="section-eyebrow">{s.category_name}</p><h2>Mit érdemes tudni?</h2><p>A {s.name} a Kleopátra {s.department_name.toLowerCase()} szolgáltatásai közé tartozik. A kezelés pontos tartalma és az alkalmazott technika a választott szalon, szakember és személyes igények alapján kerül véglegesítésre.</p></header><div className="service-detail-facts"><article className="service-detail-fact"><small>Mi a szolgáltatás?</small><h3>{s.name}</h3><p>A szolgáltatás személyre szabott konzultációval és az adott kezelés szakmai protokollja szerint történik.</p></article><article className="service-detail-fact"><small>Kinek ajánlott?</small><h3>Személyre szabott választás</h3><p>A szakember a foglalás és a helyszíni konzultáció során segít eldönteni, hogy a szolgáltatás megfelel-e az igényeidnek.</p></article><article className="service-detail-fact"><small>Időtartam</small><h3>{s.duration_minutes||30} perc</h3><p>A tényleges időtartam a szolgáltatás változatától és az egyéni körülményektől eltérhet.</p></article><article className="service-detail-fact"><small>Ár</small><h3>{normal.toLocaleString("hu-HU")} Ft-tól</h3><p>A Normál, TOP és Master szakemberi árakat szalon szerint az árlistában hasonlíthatod össze.</p></article></div><div className="service-price-box"><div className="service-price-head"><div>Szolgáltatás</div><div>Normál</div><div>TOP</div><div>Master</div></div><div className="service-price-row"><div><strong>{s.name}</strong></div><div>{money(s.level_prices?.normal??Number(s.base_price||0))}</div><div>{money(s.level_prices?.top)}</div><div>{money(s.level_prices?.master)}</div></div></div><div className="service-booking-path"><div><small>1. KÉSZ</small><b>{s.name}</b></div><div><small>2. KÖVETKEZIK</small><b>Szalon választása</b></div><div><small>3. UTÁNA</small><b>Elérhető szakember</b></div><div><small>4. VÉGÜL</small><b>Szabad időpont</b></div></div></div></section><section className="public-section public-section--soft"><div className="container public-cta"><div><h2>Következő lépés</h2><p>A szolgáltatást továbbvisszük a foglalóba. Válassz szalont, ténylegesen elérhető szakembert és szabad időpontot.</p></div><div className="public-page-hero__actions"><Link to="/prices" className="btn btn-outline">Árak összehasonlítása</Link><Link to={book} className="btn btn-primary">Tovább a foglaláshoz</Link></div></div></section></main>
}
export default ServiceDetailPage;
