import React from "react";

const CSS = String.raw`
body.kleo-mobile-menu-open{overflow:hidden!important}
@media(max-width:980px){
.kleo-modern-header{position:sticky!important;top:0!important;z-index:2000!important;background:transparent!important;border:0!important;box-shadow:none!important;padding:8px 0 0!important;pointer-events:none!important}
.kleo-modern-header__inner{width:calc(100% - 16px)!important;min-height:60px!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:12px!important;padding:7px 8px 7px 12px!important;border:1px solid rgba(255,255,255,.78)!important;border-radius:22px!important;background:rgba(255,255,255,.80)!important;box-shadow:0 18px 55px rgba(24,14,18,.10)!important;backdrop-filter:blur(24px) saturate(1.35)!important;-webkit-backdrop-filter:blur(24px) saturate(1.35)!important;pointer-events:auto!important}
.kleo-modern-header__brand{width:142px!important;display:flex!important;align-items:center!important;position:relative!important;z-index:2004!important}
.kleo-modern-header__brand img{width:100%!important;height:42px!important;display:block!important;object-fit:contain!important;object-position:left center!important}
.kleo-modern-header__menu-btn{position:relative!important;z-index:2004!important;width:44px!important;height:44px!important;display:grid!important;place-items:center!important;padding:0!important;border:1px solid rgba(32,23,25,.08)!important;border-radius:50%!important;background:#f8f3f1!important;box-shadow:0 10px 26px rgba(26,16,19,.10)!important;color:#201619!important;transition:transform .22s ease,background .22s ease!important}
.kleo-modern-header__menu-btn:active{transform:scale(.95)!important}
.kleo-modern-header__menu-icon{width:18px!important;height:14px!important;display:block!important;position:relative!important}
.kleo-modern-header__menu-icon i{position:absolute!important;left:0!important;width:18px!important;height:1.7px!important;border-radius:999px!important;background:currentColor!important;transform-origin:center!important;transition:transform .28s cubic-bezier(.2,.7,.2,1),top .28s ease!important}
.kleo-modern-header__menu-icon i:nth-child(1){top:4px!important}.kleo-modern-header__menu-icon i:nth-child(2){top:10px!important}
.kleo-modern-header.is-menu-open .kleo-modern-header__menu-icon i:nth-child(1){top:7px!important;transform:rotate(45deg)!important}.kleo-modern-header.is-menu-open .kleo-modern-header__menu-icon i:nth-child(2){top:7px!important;transform:rotate(-45deg)!important}
.kleo-modern-header__backdrop{position:fixed!important;inset:0!important;z-index:2001!important;display:block!important;border:0!important;background:rgba(25,15,20,.30)!important;backdrop-filter:blur(10px)!important;-webkit-backdrop-filter:blur(10px)!important;opacity:0!important;pointer-events:none!important;transition:opacity .28s ease!important}
.kleo-modern-header__backdrop.is-open{opacity:1!important;pointer-events:auto!important}
.kleo-modern-header__nav-wrap{position:fixed!important;top:78px!important;left:8px!important;right:8px!important;width:auto!important;height:auto!important;max-height:calc(100dvh - 88px)!important;z-index:2003!important;display:flex!important;flex-direction:column!important;align-items:stretch!important;gap:0!important;padding:22px!important;border:1px solid rgba(255,255,255,.86)!important;border-radius:28px!important;background:linear-gradient(155deg,rgba(255,255,255,.99),rgba(251,244,247,.98))!important;box-shadow:0 34px 100px rgba(30,17,23,.24)!important;overflow:auto!important;opacity:0!important;transform:translateY(-12px) scale(.985)!important;transform-origin:top center!important;pointer-events:none!important;visibility:hidden!important;transition:opacity .24s ease,transform .32s cubic-bezier(.2,.75,.2,1),visibility 0s linear .32s!important}
.kleo-modern-header__nav-wrap.is-open{opacity:1!important;transform:translateY(0) scale(1)!important;pointer-events:auto!important;visibility:visible!important;transition-delay:0s!important}
.kleo-modern-header__mobile-head{display:flex!important;align-items:center!important;justify-content:space-between!important;padding:0 0 16px!important;border-bottom:1px solid rgba(33,23,26,.08)!important}
.kleo-modern-header__mobile-kicker{display:block!important;color:#b08c74!important;font-size:9px!important;font-weight:800!important;letter-spacing:.2em!important;text-transform:uppercase!important}
.kleo-modern-header__mobile-head strong{display:block!important;margin-top:4px!important;color:#21171b!important;font-family:var(--cms-heading-font,"Montserrat"),Arial,sans-serif!important;font-size:26px!important;font-weight:520!important;letter-spacing:-.04em!important;text-transform:none!important}
.kleo-modern-header__close{width:40px!important;height:40px!important;display:grid!important;place-items:center!important;position:relative!important;border:0!important;border-radius:50%!important;background:#f5eeec!important}
.kleo-modern-header__close span{position:absolute!important;width:16px!important;height:1.5px!important;background:#21171b!important}.kleo-modern-header__close span:first-child{transform:rotate(45deg)!important}.kleo-modern-header__close span:last-child{transform:rotate(-45deg)!important}
.kleo-modern-nav{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:0 28px!important;padding:10px 0 4px!important}
.kleo-modern-nav__link{width:100%!important;min-height:62px!important;display:grid!important;grid-template-columns:28px 1fr!important;align-items:center!important;gap:4px!important;padding:0!important;border:0!important;border-bottom:1px solid rgba(31,22,25,.08)!important;color:#1f1719!important;font-family:var(--cms-heading-font,"Montserrat"),Arial,sans-serif!important;font-weight:500!important;text-transform:none!important;white-space:normal!important;transition:color .2s ease,transform .2s ease!important}
.kleo-modern-nav__index{display:block!important;color:#b79a82!important;font-size:9px!important;font-weight:800!important;letter-spacing:.08em!important}
.kleo-modern-nav__label{display:block!important;color:inherit!important;font-size:clamp(18px,2.5vw,23px)!important;font-weight:500!important;letter-spacing:-.03em!important;line-height:1.08!important}
.kleo-modern-nav__link:hover,.kleo-modern-nav__link.is-active{color:#ec008c!important;transform:translateX(2px)!important}
.kleo-modern-header__tools{display:grid!important;grid-template-columns:minmax(220px,1fr) auto!important;align-items:center!important;gap:14px!important;margin-top:16px!important;padding-top:18px!important;border-top:1px solid rgba(31,22,25,.08)!important}
.kleo-modern-header__cta{order:1!important;width:100%!important;min-height:50px!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:12px!important;padding:0 20px!important;border:0!important;border-radius:999px!important;background:linear-gradient(135deg,#ec008c,#d9007e)!important;color:#fff!important;box-shadow:0 14px 30px rgba(236,0,140,.22)!important;font-size:11px!important;font-weight:800!important;letter-spacing:.08em!important;text-transform:uppercase!important}
.kleo-modern-header__cta b{display:block!important;font-size:16px!important;font-weight:500!important}
.kleo-modern-lang{order:2!important;display:flex!important;align-items:center!important;gap:4px!important;padding:4px!important;border:1px solid rgba(30,20,24,.08)!important;border-radius:999px!important;background:#f5efec!important}
.kleo-modern-lang button{min-width:34px!important;height:30px!important;padding:0 7px!important;border:0!important;border-radius:999px!important;background:transparent!important;color:#756a6d!important;font-size:9px!important;font-weight:800!important}
.kleo-modern-lang button.is-active{background:#201619!important;color:#fff!important}
.kleo-modern-header__mobile-footer{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:12px!important;margin-top:14px!important;color:#a09799!important;font-size:8px!important;letter-spacing:.08em!important;text-transform:uppercase!important}
}
@media(max-width:600px){
.kleo-modern-header{padding-top:6px!important}.kleo-modern-header__inner{width:calc(100% - 12px)!important;min-height:56px!important;padding:6px 7px 6px 10px!important;border-radius:20px!important}.kleo-modern-header__brand{width:128px!important}.kleo-modern-header__brand img{height:38px!important}.kleo-modern-header__menu-btn{width:41px!important;height:41px!important}.kleo-modern-header__nav-wrap{top:69px!important;left:6px!important;right:6px!important;max-height:calc(100dvh - 76px)!important;padding:18px!important;border-radius:24px!important}.kleo-modern-header__mobile-head strong{font-size:23px!important}.kleo-modern-nav{grid-template-columns:1fr!important;padding-top:8px!important}.kleo-modern-nav__link{min-height:52px!important;grid-template-columns:25px 1fr!important}.kleo-modern-nav__label{font-size:19px!important}.kleo-modern-header__tools{grid-template-columns:1fr!important;gap:10px!important}.kleo-modern-lang{order:1!important;justify-self:start!important}.kleo-modern-header__cta{order:2!important;min-height:49px!important}.kleo-modern-header__mobile-footer{align-items:flex-start!important;flex-direction:column!important;gap:4px!important}}
@media(max-width:380px){.kleo-modern-header__brand{width:116px!important}.kleo-modern-header__nav-wrap{padding:16px!important}.kleo-modern-nav__link{min-height:49px!important}.kleo-modern-nav__label{font-size:18px!important}}
`;

export default function MobileLuxuryStyles(){
  return <style data-kleo-critical="mobile-luxury-2026">{CSS}</style>;
}
