import React from "react";

const CSS = String.raw`
body.kleo-mobile-menu-open{overflow:hidden!important}
@media(max-width:980px){
.kleo-modern-header{position:sticky!important;top:0!important;z-index:2000!important;background:transparent!important;border:0!important;box-shadow:none!important;padding:10px 0 0!important;pointer-events:none!important}
.kleo-modern-header__inner{width:calc(100% - 20px)!important;min-height:62px!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:12px!important;padding:8px 10px!important;border:1px solid rgba(255,255,255,.72)!important;border-radius:24px!important;background:rgba(255,255,255,.78)!important;box-shadow:0 18px 55px rgba(24,14,18,.10)!important;backdrop-filter:blur(24px) saturate(1.35)!important;-webkit-backdrop-filter:blur(24px) saturate(1.35)!important;pointer-events:auto!important}
.kleo-modern-header__brand{width:146px!important;display:flex!important;align-items:center!important;position:relative!important;z-index:2004!important}
.kleo-modern-header__brand img{width:100%!important;height:44px!important;display:block!important;object-fit:contain!important;object-position:left center!important}
.kleo-modern-header__menu-btn{position:relative!important;z-index:2004!important;width:46px!important;height:46px!important;display:grid!important;place-items:center!important;padding:0!important;border:1px solid rgba(32,23,25,.08)!important;border-radius:50%!important;background:rgba(250,247,244,.94)!important;box-shadow:0 10px 26px rgba(26,16,19,.10)!important;color:#201619!important;transition:transform .22s ease,background .22s ease!important}
.kleo-modern-header__menu-btn:active{transform:scale(.95)!important}
.kleo-modern-header__menu-label{display:none!important}
.kleo-modern-header__menu-icon{width:18px!important;height:14px!important;display:block!important;position:relative!important}
.kleo-modern-header__menu-icon i{position:absolute!important;left:0!important;width:18px!important;height:1.6px!important;border-radius:999px!important;background:currentColor!important;transform-origin:center!important;transition:transform .28s cubic-bezier(.2,.7,.2,1),opacity .2s ease,top .28s ease!important}
.kleo-modern-header__menu-icon i:nth-child(1){top:3px!important}.kleo-modern-header__menu-icon i:nth-child(2){top:6.5px!important}.kleo-modern-header__menu-icon i:nth-child(3){top:10px!important}
.kleo-modern-header.is-menu-open .kleo-modern-header__menu-icon i:nth-child(1){top:6.5px!important;transform:rotate(45deg)!important}.kleo-modern-header.is-menu-open .kleo-modern-header__menu-icon i:nth-child(2){opacity:0!important}.kleo-modern-header.is-menu-open .kleo-modern-header__menu-icon i:nth-child(3){top:6.5px!important;transform:rotate(-45deg)!important}
.kleo-modern-header__backdrop{position:fixed!important;inset:0!important;z-index:2001!important;display:block!important;border:0!important;background:rgba(25,15,20,.28)!important;backdrop-filter:blur(10px)!important;-webkit-backdrop-filter:blur(10px)!important;opacity:0!important;pointer-events:none!important;transition:opacity .28s ease!important}
.kleo-modern-header__backdrop.is-open{opacity:1!important;pointer-events:auto!important}
.kleo-modern-header__nav-wrap{position:fixed!important;top:84px!important;left:10px!important;right:10px!important;width:auto!important;height:auto!important;max-height:calc(100dvh - 96px)!important;z-index:2003!important;display:flex!important;flex-direction:column!important;align-items:stretch!important;gap:0!important;padding:22px!important;border:1px solid rgba(255,255,255,.82)!important;border-radius:30px!important;background:linear-gradient(160deg,rgba(255,255,255,.98),rgba(251,246,246,.97))!important;box-shadow:0 30px 90px rgba(30,17,23,.22)!important;overflow:auto!important;opacity:0!important;transform:translateY(-14px) scale(.985)!important;transform-origin:top center!important;pointer-events:none!important;visibility:hidden!important;transition:opacity .26s ease,transform .32s cubic-bezier(.2,.75,.2,1),visibility 0s linear .32s!important}
.kleo-modern-header__nav-wrap.is-open{opacity:1!important;transform:translateY(0) scale(1)!important;pointer-events:auto!important;visibility:visible!important;transition-delay:0s!important}
.kleo-modern-header__mobile-head{display:flex!important;align-items:center!important;justify-content:space-between!important;padding:0 2px 16px!important;border-bottom:1px solid rgba(33,23,26,.08)!important;color:#9b7a67!important;font-size:10px!important;font-weight:800!important;letter-spacing:.20em!important;text-transform:uppercase!important}
.kleo-modern-header__mobile-head button{display:none!important}
.kleo-modern-nav{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:0 28px!important;padding:12px 0 8px!important}
.kleo-modern-nav__link{position:relative!important;width:100%!important;min-height:62px!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;padding:0 0 0 30px!important;border:0!important;border-bottom:1px solid rgba(31,22,25,.08)!important;color:#1f1719!important;font-family:var(--cms-heading-font,"Montserrat"),Arial,sans-serif!important;font-size:clamp(18px,2.5vw,24px)!important;font-weight:500!important;letter-spacing:-.025em!important;line-height:1.08!important;text-transform:none!important;white-space:normal!important;transition:color .2s ease,transform .2s ease!important}
.kleo-modern-nav__link::before{content:counter(kleo-nav,decimal-leading-zero)!important;counter-increment:kleo-nav!important;position:absolute!important;left:0!important;top:50%!important;transform:translateY(-50%)!important;color:#b79a82!important;font-size:9px!important;font-weight:800!important;letter-spacing:.08em!important}
.kleo-modern-nav{counter-reset:kleo-nav!important}
.kleo-modern-nav__link>span{display:none!important}
.kleo-modern-nav__link:hover,.kleo-modern-nav__link.is-active{color:#ec008c!important;transform:translateX(2px)!important}
.kleo-modern-header__tools{display:grid!important;grid-template-columns:auto minmax(180px,1fr)!important;align-items:center!important;gap:14px!important;margin-top:14px!important;padding-top:18px!important;border-top:1px solid rgba(31,22,25,.08)!important}
.kleo-modern-lang{display:flex!important;align-items:center!important;gap:4px!important;padding:4px!important;border:1px solid rgba(30,20,24,.08)!important;border-radius:999px!important;background:#f5efec!important}
.kleo-modern-lang button{min-width:34px!important;height:30px!important;padding:0 7px!important;border:0!important;border-radius:999px!important;background:transparent!important;color:#756a6d!important;font-size:9px!important;font-weight:800!important}
.kleo-modern-lang button.is-active{background:#201619!important;color:#fff!important}
.kleo-modern-header__cta{width:100%!important;min-height:48px!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;padding:0 20px!important;border:0!important;border-radius:999px!important;background:linear-gradient(135deg,#ec008c,#d9007e)!important;color:#fff!important;box-shadow:0 14px 30px rgba(236,0,140,.22)!important;font-size:11px!important;font-weight:800!important;letter-spacing:.08em!important;text-transform:uppercase!important}
.kleo-modern-header__mobile-note{display:block!important;margin:14px 0 0!important;color:#a59a9e!important;font-size:9px!important;letter-spacing:.08em!important;text-align:center!important;text-transform:uppercase!important}
}
@media(max-width:600px){
.kleo-modern-header{padding-top:7px!important}.kleo-modern-header__inner{width:calc(100% - 14px)!important;min-height:58px!important;padding:6px 8px 6px 10px!important;border-radius:21px!important}.kleo-modern-header__brand{width:132px!important}.kleo-modern-header__brand img{height:40px!important}.kleo-modern-header__menu-btn{width:42px!important;height:42px!important}.kleo-modern-header__nav-wrap{top:72px!important;left:7px!important;right:7px!important;max-height:calc(100dvh - 80px)!important;padding:18px!important;border-radius:26px!important}.kleo-modern-nav{grid-template-columns:1fr!important;padding-top:8px!important}.kleo-modern-nav__link{min-height:53px!important;padding-left:27px!important;font-size:19px!important}.kleo-modern-header__tools{grid-template-columns:1fr!important;gap:10px!important}.kleo-modern-lang{justify-self:start!important}.kleo-modern-header__cta{min-height:48px!important}.kleo-modern-header__mobile-head{padding-bottom:12px!important}}
@media(max-width:380px){.kleo-modern-header__brand{width:120px!important}.kleo-modern-header__nav-wrap{padding:16px!important}.kleo-modern-nav__link{font-size:18px!important}}
`;

export default function MobileLuxuryStyles(){
  return <style data-kleo-critical="mobile-luxury-2026">{CSS}</style>;
}
