export const MOTIVATION_QUOTES_V13 = [
  "A következetesség csendben építi azt, amit a lelkesedés elkezd.",
  "A mai kis lépés holnap már megtett út.",
  "Nem kell tökéletesnek lenned, csak újra el kell indulnod.",
  "A fejlődés sokszor akkor történik, amikor még nem látványos.",
  "A fegyelem akkor dolgozik érted, amikor a kedved éppen nem.",
  "Minden erős rutin egyetlen ismétléssel kezdődött.",
  "A kitartás nem hangos, mégis messzebbre visz, mint a lendület.",
  "A saját tempód is tempó, ha előre visz.",
  "A változás nem egy nagy döntés, hanem sok kicsi igen.",
  "A cél nem az, hogy könnyű legyen, hanem hogy megérje.",
  "Az eredmény a rendszeresen megtett apró dolgok összege.",
  "A mai munka a holnapi magabiztosság alapja.",
  "A haladásnak nem kell látványosnak lennie ahhoz, hogy valós legyen.",
  "A szokásaid gyakran hamarabb változtatják meg az életedet, mint a terveid.",
  "A nehezebb napokon végzett minimum is számít.",
  "A fókusz nem több feladatot, hanem kevesebb zajt jelent.",
  "A stabil eredményt a stabil ismétlés hozza.",
  "A következő jó döntés mindig fontosabb, mint az előző hiba.",
  "A türelem nem várakozás, hanem kitartó munka eredménykényszer nélkül.",
  "A fejlődéshez néha nem gyorsítani kell, hanem folytatni.",
  "Ha ma csak egy dolgot teszel meg jól, legyen az a következő lépés.",
  "A komfortzóna széle gyakran a fejlődés kezdete.",
  "A motiváció hullámzik, a rendszer megtart.",
  "A kis győzelmekből lesz az a nap, amire később büszke leszel.",
  "A kitartó ember nem mindig erősebb, csak tovább marad játékban.",
  "A jövőbeli éned a mai ismétléseidből épül.",
  "A halogatás helyett válassz egy kétperces kezdést.",
  "A lendület gyakran az első mozdulat után érkezik.",
  "A fejlődés nem verseny másokkal, hanem megállapodás önmagaddal.",
  "Nem kell mindent egyszerre megoldani; elég a következő helyes lépés.",
  "A kitartás akkor válik erővé, amikor már senki nem tapsol hozzá.",
  "Az önbizalom gyakran abból születik, hogy betartod a saját ígéreteidet.",
  "A jó napot nem mindig megtaláljuk; sokszor felépítjük.",
  "A fejlődés egyik jele, hogy gyorsabban visszatalálsz a jó ritmushoz.",
  "A mai figyelem többet ér, mint a holnapi tökéletes terv.",
  "A következetes közepes teljesítmény gyakran legyőzi a ritka csúcsteljesítményt.",
  "A változás akkor marad meg, amikor szokássá válik.",
  "Az energiádat arra költsd, amit ténylegesen befolyásolni tudsz.",
  "Egy nehéz nap nem írja felül az eddig megtett utat.",
  "A céljaidnak nem több idő kell, hanem több elsőbbség.",
];

export const BEAUTY_QUOTES_V13 = [
  "A szépség akkor él, amikor az önazonosság és a gondoskodás találkozik.",
  "A ragyogás sokszor a figyelemmel kezdődik, nem a tükörrel.",
  "A stílus nem másolat, hanem következetesen vállalt saját választás.",
  "A szépség részletekben mutatkozik meg, de egészében hat.",
  "A gondoskodás láthatóvá teszi azt, amit önmagadban értékelsz.",
  "A jó megjelenés nem álarc, hanem rendezett önkifejezés.",
  "A természetes hatás mögött gyakran tudatos részletek állnak.",
  "A szépség nem egyetlen szabály, hanem harmónia sok apró döntés között.",
  "A magabiztosság az egyik legerősebb kiegészítő.",
  "A jól ápoltság üzenete egyszerű: fontos vagyok magamnak.",
  "A frissesség nem életkor, hanem jelenlét.",
  "A szép részletek akkor működnek igazán, amikor nem versenyeznek egymással.",
  "A stílus ott kezdődik, ahol a trendet személyessé teszed.",
  "A ragyogás nem feltétlenül fényes; néha egyszerűen kiegyensúlyozott.",
  "A szépségápolás jó esetben nem javítgatás, hanem figyelmes karbantartás.",
  "A harmonikus megjelenésben minden részlet ugyanazt a történetet meséli.",
  "Az ápoltság csendes luxus: nem kiabál, mégis észrevehető.",
  "A szépség legjobb kerete az, amikor kényelmesen érzed magad önmagadban.",
  "A jó frizura mozgást ad az arcnak, a jó tartás pedig az egész megjelenésnek.",
  "A bőrápolásban a rendszeresség többet ér, mint a kapkodó túlzás.",
  "A kifinomultság gyakran abból születik, amit tudatosan elhagysz.",
  "A szép megjelenés nem feltétlenül több, hanem pontosabban választott részlet.",
  "Az önazonos stílus nem kér engedélyt minden új trendtől.",
  "A gondosan választott részletek együtt nagyobb hatást keltenek, mint külön-külön.",
  "A szépségben is működik az arányérzék: elég, ami kiemel, nem elfed.",
  "A jó ápoltság nem alkalomhoz kötött, hanem rutinból épül.",
  "A természetesség és a precizitás nem ellentétei egymásnak.",
  "A megjelenés akkor hiteles, amikor illik a személyiségedhez és a napodhoz.",
  "A haj, a bőr és a tartás együtt adja az első benyomás ritmusát.",
  "A szépség egyik formája az, amikor minden a helyén van, de semmi sincs túljátszva.",
  "A stílus akkor működik, ha nem csak jól néz ki, hanem jól is érzed magad benne.",
  "A ragyogásnak van technikája, de az alapja mindig a gondoskodás.",
  "A jó megjelenés nem elrejti, hanem rendezi a karaktert.",
  "A szépség nem egyetlen pillanat; inkább sok apró, ismételt figyelmesség.",
  "A finom részletek sokszor tovább maradnak emlékezetesek, mint a nagy gesztusok.",
  "A valódi elegancia nem túl sok, hanem pont elég.",
  "A gondoskodásból születő magabiztosság mindig jobban áll, mint a megfelelési kényszer.",
  "A szépség akkor a legerősebb, amikor nem akar másnak látszani, mint ami.",
  "A jó stílus egyszerre rendezett, személyes és könnyed.",
  "A friss megjelenés egyik titka a következetes, egyszerű rutin.",
];

export const GYM_TIPS_V13 = [
  "Guggolás: mellkas maradjon nyitva, törzs feszes, a csípő induljon hátra, a térd kövesse a lábfej irányát.",
  "Plank: feszítsd meg a hasat és a farizmot, tarts semleges gerincet, ne engedd beesni a derekat.",
  "Fekvőtámasz: a tested maradjon egy vonalban, a könyök ne nyíljon teljesen oldalra, a törzs végig legyen feszes.",
  "Kitörés: lépj stabilan, az elöl lévő térd kövesse a lábfej irányát, a törzs maradjon magas.",
  "Evezés: előbb húzd hátra és lefelé a lapockát, aztán vezesd a könyököt a törzs mellett hátra.",
  "Vállból nyomás: bordák maradjanak kontroll alatt, a törzs legyen feszes, ne homoríts túl.",
  "Csípőemelés: a mozdulat tetején feszíts rá a farizomra, de ne a derekadból told túl a mozgást.",
  "Román felhúzás: puha térd, csípő hátra, hát semleges, a súly maradjon közel a lábhoz.",
  "Oldalemelés: kisebb súllyal dolgozz kontrolláltan, a vállat ne húzd fel a füledhez.",
  "Bicepsz: a felkar maradjon közel a törzshöz, ne lendületből emeld a súlyt.",
  "Tricepsz letolás: a könyök maradjon a törzs mellett, csak az alkar mozogjon nagyot.",
  "Vádliemelés: teljes, kontrollált mozgástartományban dolgozz, a felső ponton tarts rövid feszítést.",
  "Hasprés: ne a nyakad húzd; a bordakosarat közelítsd a medencéhez kontrolláltan.",
  "Dead bug: a derekat tartsd stabilan, csak addig nyújtsd a kart és lábat, amíg nem veszted el a törzsfeszítést.",
  "Goblet squat: a súlyt tartsd közel a mellkashoz, ülj le a csípővel a két láb közé, maradj stabil talpon.",
  "Lat pulldown: ne rángasd a rudat; mellkas enyhén emelt, könyök lefelé és hátra haladjon.",
  "Step-up: az elöl lévő láb dolgozzon, ne lökd fel magad túl erősen a hátul lévő lábbal.",
  "Farmer's walk: magas tartás, feszes törzs, rövid kontrollált lépések, a váll ne essen előre.",
  "Mountain climber: a medence maradjon stabil, a térdet kontrolláltan húzd előre, ne csak a tempót hajszold.",
  "Face pull: a kötelet szemmagasság felé húzd, könyök szélesen, lapocka kontrolláltan zárjon.",
  "Mellnyomás: lapocka legyen stabil, a csukló maradjon a könyök fölött, a mozgás legyen kontrollált.",
  "Combhajlítás: ne kapkodj; a visszaengedés legyen legalább olyan kontrollált, mint a behúzás.",
  "Lábtoló: a derekad maradjon a támlán, a térd kövesse a lábfej irányát, ne zárd ki erőből a térdet.",
  "Edzés közben a technika legyen az első: ha szétesik a forma, csökkents súlyt vagy ismétlést.",
];
